global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "panol-backend"
    scheme: https
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - panol-backend-staging-perf-369729778197.us-central1.run.app
